storage:
  type: sqlite
  mysql:
    host: localhost
    port: 3306
    database: levelsx
    user: root
    password: ''
moneyReward: 100.0
itemReward: DIAMOND
itemRewards: {}
levelCap: 100
challengeGoals:
  MOB_KILLS: 10
  DAMAGE_TAKEN: 500
  MONEY_EARNED: 1000
  MONEY_SPENT: 1000
  KILOMETERS_TRAVELED: 5
