# =====================================
#  LevelsX Plugin Configuration File
# =====================================

# --- Storage Settings ---
storage:
  # Choose your storage method: 'sqlite' or 'mysql'
  type: sqlite

  # MySQL settings (only used if type: mysql)
  mysql:
    host: localhost    # Database host
    port: 3306         # Database port
    database: levelsx      # Database name
    user: root         # Database user
    password: ''           # Database password

# --- Level-Up Rewards ---
# Rewards given to a player upon leveling up
moneyReward: 100.0        # Amount of in-game currency
itemReward: DIAMOND       # Single item reward (e.g., DIAMOND)
itemRewards: {}           # Multiple item rewards (format: ITEM_NAME: AMOUNT)

# --- General Limits ---
levelCap: 100             # Maximum achievable level
autosave: 5               # Minutes between automatic data saves

# --- Challenge Goals ---
# Separate goals for daily and weekly challenges
dailyGoals:
  MOB_KILLS: 10
  DAMAGE_TAKEN: 500
  MONEY_EARNED: 1000
  MONEY_SPENT: 1000
  KILOMETERS_TRAVELED: 5
weeklyGoals:
  MOB_KILLS: 50
  DAMAGE_TAKEN: 2500
  MONEY_EARNED: 5000
  MONEY_SPENT: 5000
  KILOMETERS_TRAVELED: 25

# --- Challenge Rewards ---
# Rewards granted when completing challenges
challengeRewards:
  daily:
    xp: 20
    money: 0.0
    types:
      MOB_KILLS: {xp: 20, money: 0.0}
      DAMAGE_TAKEN: {xp: 20, money: 0.0}
      MONEY_EARNED: {xp: 20, money: 0.0}
      MONEY_SPENT: {xp: 20, money: 0.0}
      KILOMETERS_TRAVELED: {xp: 20, money: 0.0}
  weekly:
    xp: 50
    money: 0.0
    types:
      MOB_KILLS: {xp: 50, money: 0.0}
      DAMAGE_TAKEN: {xp: 50, money: 0.0}
      MONEY_EARNED: {xp: 50, money: 0.0}
      MONEY_SPENT: {xp: 50, money: 0.0}
      KILOMETERS_TRAVELED: {xp: 50, money: 0.0}

# --- Kill Rewards ---
killRewards:
  mobs:
    enabled: true
    xp: 10
    money: 0.0
  players:
    enabled: true
    xp: 25
    money: 0.0

# --- Scoreboard Defaults ---
scoreboard:
  order: [LEVEL, XP, PROGRESS, BALANCE, KILLS, MOB_KILLS, DEATHS, KM]
  enabled:
    LEVEL: true
    BALANCE: false
    XP: true
    PROGRESS: true
    KILLS: false
    MOB_KILLS: false
    DEATHS: false
    KM: false
